language: python

python:
  - "3.7"
  - "3.8"

cache:
  - pip

before_install:
  - travis_retry sudo apt-get install -y libblas-dev liblapack-dev libopenblas-dev

# command to install dependencies
install:
  - travis_retry pip install -q -r requirements.txt
  - pip install -e .

# command to run tests
script:
  # install necessary packages to run tests and run tests
  - travis_retry pip install -q pytest pytest-cov codecov
  - pytest --cov=./
  # test installation
  - python setup.py install
  # install packages for docs and make docs
  - travis_retry pip install -q ipython Sphinx sphinx-gallery numpydoc sphinx-bootstrap-theme
  - cd docs
  - sphinx-apidoc -o source/autodoc ../moten
  - sphinx-autogen source/index.rst
  - make html && cd ..
  # Tell GitHub not to use jekyll to compile the docs
  - touch docs/build/html/.nojekyll

after_success:
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
      # push only once
      python: "3.8"
    local_dir: docs/build/html/
