language: python

python:
  - "3.7"

cache:
  - pip

before_install:
  - travis_retry sudo apt-get install -y libblas-dev liblapack-dev libopenblas-dev ffmpeg libx264-dev

# command to install dependencies and necessary packages to run tests
install:
  - travis_retry pip install -q -r test_requirements.txt
  - pip install -e .

# command to run tests
script:
  # run tests
  - pytest -v --cov=./
  # test installation
  - python setup.py install
  # install packages for docs and make docs
  - travis_retry pip install -q ipython Sphinx sphinx-gallery numpydoc sphinx-rtd-theme sphinx-bootstrap-theme
  - cd docs
  # custom makefile directive
  - make githubio-docs && cd ..

after_success:
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
      # push only once
      python: "3.7"
    local_dir: docs/build/html/
